version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Install executable
          command: stack install
      - run:
          name: current directory
          command: echo "# check for stack?" ; ls -la; echo "# show .stack-work"; ls -la .stack-work; echo "# show root/"; ls -la /root; echo "# show root stack"; ls -la /root/.stack
      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
      - store_artifacts: # upload build artifact for display in CircleCi
          path: ~/.local/bin/circleci-demo-haskell-exe
          destination: circleci-demo-haskell-exe
